language: ruby
addons:
  postgresql: "9.4"
rvm:
  - "2.2.0"
before_install:
  - cp config/samples/database.travis.yml config/database.yml
install:
  - bundle install --without production
  - bin/rake db:setup